-- ============================================================
-- ҚҰЖАТ ПАПКАЛАРЫ (document folders)
-- Supabase → SQL Editor-ге кіріп, осы файлдың бәрін көшіріп,
-- БІР РЕТ "Run" басыңыз. Ескі кестелерге (news, documents, ...)
-- ешбір тимайды — тек жаңа папка функциясы қосылады.
-- ============================================================

-- 1) Папкалар кестесі.
--    password = NULL немесе бос жол  → папка АШЫҚ, бәрі көре алады.
--    password = мәтін                → папка ҮЙДЕ, дәл сол сөзді білетін
--                                       адам ғана аша алады (сіз және директор).
create table if not exists public.document_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  password text,
  created_at timestamptz default now()
);

alter table public.document_folders enable row level security;

-- Папка кестесіне тікелей қатынау (құру/өңдеу/өшіру/оқу) тек admin-ге ғана
-- ашық. Қалған келушілер папканы төмендегі екі функция арқылы ғана көреді —
-- сол функциялар паролдің өз мәнін ешқашан жібермейді, тек "құлыпты ма?"
-- деген true/false қайтарады.
drop policy if exists "Admin can manage document_folders" on public.document_folders;
create policy "Admin can manage document_folders"
  on public.document_folders for all
  to authenticated
  using (public.is_kitapverse_admin())
  with check (public.is_kitapverse_admin());

-- 2) documents кестесіне "қай папкада тұр" бағаны.
--    Папка өшірілсе, ішіндегі құжаттар жоғалмайды — "Жалпы құжаттар"
--    тобына автоматты түрде қайтады (SET NULL).
alter table public.documents
  add column if not exists folder_id bigint references public.document_folders(id) on delete set null;

-- 3) Папка тізімін көрсету — паролдің өзі емес, тек "құлыпты ма" (true/false)
--    және ішінде неше құжат бар екені қайтады.
create or replace function public.list_document_folders()
returns table(id bigint, name text, is_locked boolean, doc_count bigint)
language sql stable security definer set search_path = public as $$
  select f.id, f.name,
         (f.password is not null and length(trim(f.password)) > 0) as is_locked,
         (select count(*) from public.documents d where d.folder_id = f.id) as doc_count
  from public.document_folders f
  order by f.created_at desc;
$$;
grant execute on function public.list_document_folders() to anon, authenticated;

-- 4) Папка ішіндегі құжаттарды алу. Пароль осы функцияның ІШІНДЕ
--    серверде тексеріледі — қате пароль берілсе, ешбір құжат қайтпайды.
create or replace function public.get_folder_documents(p_folder_id bigint default null, p_password text default null)
returns setof public.documents
language plpgsql security definer set search_path = public as $$
declare folder_pw text;
begin
  if p_folder_id is null then
    return query select * from public.documents where folder_id is null order by created_at desc;
  end if;

  select password into folder_pw from public.document_folders where id = p_folder_id;
  if folder_pw is not null and length(trim(folder_pw)) > 0 then
    if p_password is null or trim(p_password) <> folder_pw then
      raise exception 'invalid password';
    end if;
  end if;

  return query select * from public.documents where folder_id = p_folder_id order by created_at desc;
end; $$;
grant execute on function public.get_folder_documents(bigint, text) to anon, authenticated;

-- ДАЙЫН. Енді сайттағы әкімшілік панельде (Сайт → Құжаттар) "Жаңа папка
-- құру" пайда болады: атауын өзіңіз жазасыз, құпиясөзді бос қалдырсаңыз
-- папка ашық болады, ал құпиясөз қойсаңыз — тек сол құпиясөзді білетін
-- адам аша алады.
--
-- МАҢЫЗДЫ ЕСКЕРТУ: пароль осы жерде папканың ІШІНДЕГІ ТІЗІМДІ (қандай
-- құжаттар бар, олардың атауы) жасырады. Ал файлдың өзі Supabase Storage-тің
-- ашық "documents" қорабында тұрады, яғни тікелей файл сілтемесін білетін
-- адам (мысалы, оны бөліскен болса) құпиясөзсіз аша алады. Өте құпия
-- құжаттар үшін бұл жеткілікті қорғаныс емес — тек "кездейсоқ көрмесін"
-- дегенге ғана сенімді.
