-- ================================================================
-- KITAPVERSE FINAL DATABASE MIGRATION
-- Run this ONE file in Supabase SQL Editor.
-- It includes the base site additions, daily quiz, Battles, native quests,
-- and Battle rewards (+50 class / +10 best student).
-- ================================================================

-- Run this ONCE in Supabase SQL Editor.
-- This adds the fields the website needs to the tables you already created.
alter table public.news
  add column if not exists published_date date default current_date;

alter table public.documents
  add column if not exists file_name text;

alter table public.documents
  add column if not exists storage_path text;

-- Optional: make existing news have today's date if the new column is null.
update public.news set published_date = current_date where published_date is null;

-- ===== New table: achievements (Жетістіктер) =====
-- This table did not exist before, so it needs RLS policies of its own.
-- If your news/documents tables use different policy names, adjust to match.
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  icon text default '🏆',
  title text not null,
  description text not null,
  created_at timestamptz default now()
);

alter table public.achievements enable row level security;

-- Anyone (including anonymous site visitors) can read achievements.
drop policy if exists "Public can read achievements" on public.achievements;
create policy "Public can read achievements"
  on public.achievements for select
  to anon, authenticated
  using (true);

-- Only a signed-in admin (Supabase Auth user) can add/edit/delete achievements.
drop policy if exists "Authenticated can manage achievements" on public.achievements;
create policy "Authenticated can manage achievements"
  on public.achievements for all
  to authenticated
  using (true)
  with check (true);

-- ===== Make sure edit/delete also work on news & documents =====
-- Your original setup likely only had INSERT + SELECT policies for the admin
-- (since the old site could only add, never edit/delete). These add UPDATE and
-- DELETE for the signed-in admin so the new edit/delete buttons work too.
drop policy if exists "Authenticated can update news" on public.news;
create policy "Authenticated can update news"
  on public.news for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated can delete news" on public.news;
create policy "Authenticated can delete news"
  on public.news for delete to authenticated using (true);

drop policy if exists "Authenticated can update documents" on public.documents;
create policy "Authenticated can update documents"
  on public.documents for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated can delete documents" on public.documents;
create policy "Authenticated can delete documents"
  on public.documents for delete to authenticated using (true);

-- ===== KITAPVERSE: library_books (Кітапхана) =====
create table if not exists public.library_books (
  id bigint generated by default as identity primary key,
  icon text default '📕',
  title text not null,
  author text,
  description text,
  created_at timestamptz default now()
);

alter table public.library_books enable row level security;

drop policy if exists "Public can read library_books" on public.library_books;
create policy "Public can read library_books"
  on public.library_books for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage library_books" on public.library_books;
create policy "Authenticated can manage library_books"
  on public.library_books for all
  to authenticated
  using (true)
  with check (true);

-- ===== KITAPVERSE: class_xp (Рейтинг тақтасы) =====
-- One row per class (e.g. "7А"), xp is the running total.
-- The admin form adds points to this total; it never needs student logins.
create table if not exists public.class_xp (
  id bigint generated by default as identity primary key,
  class_name text not null unique,
  xp integer not null default 0,
  updated_at timestamptz default now()
);

alter table public.class_xp enable row level security;

drop policy if exists "Public can read class_xp" on public.class_xp;
create policy "Public can read class_xp"
  on public.class_xp for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage class_xp" on public.class_xp;
create policy "Authenticated can manage class_xp"
  on public.class_xp for all
  to authenticated
  using (true)
  with check (true);

-- ===== News photo support =====
-- Photos are stored in the same "documents" storage bucket, under a "news/" path.
alter table public.news
  add column if not exists photo_url text;

alter table public.news
  add column if not exists photo_path text;

-- ===== Library: PDF books + grade grouping (6–10 сынып) =====
alter table public.library_books
  add column if not exists grade int;

alter table public.library_books
  add column if not exists pdf_url text;

alter table public.library_books
  add column if not exists pdf_path text;

-- ===== Site settings (key/value) — used for the Google Forms link for Квесттер =====
create table if not exists public.kv_settings (
  key text primary key,
  value text
);

alter table public.kv_settings enable row level security;

drop policy if exists "Public can read kv_settings" on public.kv_settings;
create policy "Public can read kv_settings"
  on public.kv_settings for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage kv_settings" on public.kv_settings;
create policy "Authenticated can manage kv_settings"
  on public.kv_settings for all
  to authenticated
  using (true)
  with check (true);

-- ===== Quiz questions (Викторина) — admin-authored multiple choice =====
create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('a','b','c','d')),
  created_at timestamptz default now()
);

alter table public.quiz_questions enable row level security;

drop policy if exists "Public can read quiz_questions" on public.quiz_questions;
create policy "Public can read quiz_questions"
  on public.quiz_questions for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage quiz_questions" on public.quiz_questions;
create policy "Authenticated can manage quiz_questions"
  on public.quiz_questions for all
  to authenticated
  using (true)
  with check (true);

-- ===== Quiz attempts — one row per student submission, feeds Battle + student rating =====
create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  student_name text not null,
  class_name text not null,
  score int not null,
  total int not null,
  created_at timestamptz default now()
);

alter table public.quiz_attempts enable row level security;

-- Anyone can read results (needed for the public Battle/rating boards) and
-- anyone (including anonymous students) can submit an attempt — but never
-- update or delete one, so results cannot be tampered with after submission.
drop policy if exists "Public can read quiz_attempts" on public.quiz_attempts;
create policy "Public can read quiz_attempts"
  on public.quiz_attempts for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can submit quiz_attempts" on public.quiz_attempts;
create policy "Public can submit quiz_attempts"
  on public.quiz_attempts for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Authenticated can delete quiz_attempts" on public.quiz_attempts;
create policy "Authenticated can delete quiz_attempts"
  on public.quiz_attempts for delete
  to authenticated
  using (true);

-- ===== Rewards (Марапаттау) =====
create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  position text not null,
  icon text default '🏆',
  title text not null,
  created_at timestamptz default now()
);

alter table public.rewards enable row level security;

drop policy if exists "Public can read rewards" on public.rewards;
create policy "Public can read rewards"
  on public.rewards for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage rewards" on public.rewards;
create policy "Authenticated can manage rewards"
  on public.rewards for all
  to authenticated
  using (true)
  with check (true);


-- DAILY QUIZ / ONE CHANCE MIGRATION
-- Run once in Supabase SQL Editor.
-- After this migration the public website can see the question/options,
-- but cannot read the correct answer. The answer is checked inside RPC.

-- 1) Link each new attempt to the exact daily question.
alter table public.quiz_attempts
  add column if not exists question_id bigint references public.quiz_questions(id) on delete cascade;

-- 2) One attempt for one student identity on one question.
-- Spaces/case and Latin/Cyrillic look-alike class letters are normalized.
create unique index if not exists quiz_attempts_one_chance_idx
on public.quiz_attempts (
  question_id,
  lower(regexp_replace(trim(student_name), '\s+', '', 'g')),
  translate(upper(regexp_replace(trim(class_name), '\s+', '', 'g')), 'ABEKMHOPCTXY', 'АВЕКМНОРСТХУ')
)
where question_id is not null;

-- 3) Public question view WITHOUT correct_option.
drop view if exists public.quiz_questions_public;
create view public.quiz_questions_public as
select id, question, option_a, option_b, option_c, option_d, created_at
from public.quiz_questions;

grant select on public.quiz_questions_public to anon, authenticated;

-- Do not let anonymous visitors read the source table, because it contains
-- correct_option. Authenticated admins still have access through their policy.
revoke select on public.quiz_questions from anon;

-- 4) Server-side submission lives further down in this file (V3 section),
-- since the daily-quiz batching feature replaces this simple version.
-- (An early draft of submit_daily_quiz was removed here — keeping two
-- "create or replace" definitions around was dead weight, not a bug, but
-- worth cleaning up.)

-- 5) Make the public result/rating refresh naturally from the attempts table.
-- Existing old attempts (question_id IS NULL) are preserved in the historical
-- student rating, while all new daily attempts are protected by question_id.


-- Run this ONCE in Supabase SQL Editor (after supabase-migration.sql).
-- Adds the Battle feature: scheduled class-vs-class events with their own
-- quiz-style questions and a countdown timer on the site.

-- ===== battles: one row per battle event (admin creates: title, classes, date) =====
create table if not exists public.battles (
  id bigint generated by default as identity primary key,
  title text not null,
  classes text not null,               -- e.g. "8А, 9Б" (free text, comma separated)
  battle_date timestamptz not null,    -- when the battle starts (countdown target)
  created_at timestamptz default now()
);

alter table public.battles enable row level security;

drop policy if exists "Public can read battles" on public.battles;
create policy "Public can read battles"
  on public.battles for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage battles" on public.battles;
create policy "Authenticated can manage battles"
  on public.battles for all
  to authenticated
  using (true)
  with check (true);

-- ===== battle_questions: quiz questions that belong to one specific battle =====
create table if not exists public.battle_questions (
  id bigint generated by default as identity primary key,
  battle_id bigint not null references public.battles(id) on delete cascade,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('a','b','c','d')),
  created_at timestamptz default now()
);

alter table public.battle_questions enable row level security;

drop policy if exists "Public can read battle_questions" on public.battle_questions;
create policy "Public can read battle_questions"
  on public.battle_questions for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage battle_questions" on public.battle_questions;
create policy "Authenticated can manage battle_questions"
  on public.battle_questions for all
  to authenticated
  using (true)
  with check (true);

-- ===== battle_attempts: one row per student submission for a battle =====
create table if not exists public.battle_attempts (
  id bigint generated by default as identity primary key,
  battle_id bigint not null references public.battles(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  score int not null,
  total int not null,
  created_at timestamptz default now()
);

alter table public.battle_attempts enable row level security;

drop policy if exists "Public can read battle_attempts" on public.battle_attempts;
create policy "Public can read battle_attempts"
  on public.battle_attempts for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can submit battle_attempts" on public.battle_attempts;
create policy "Public can submit battle_attempts"
  on public.battle_attempts for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Authenticated can delete battle_attempts" on public.battle_attempts;
create policy "Authenticated can delete battle_attempts"
  on public.battle_attempts for delete
  to authenticated
  using (true);



-- V3: scheduled daily quiz batches + 30-minute Battles.
-- Run after the existing site migrations.

-- ================================================================
-- DAILY QUIZ: admin adds a batch, each question lives for exactly 24h.
-- ================================================================
create table if not exists public.quiz_batches (
  id bigint generated by default as identity primary key,
  title text not null default 'Күнделікті викторина',
  start_at timestamptz not null,
  created_at timestamptz not null default now()
);
alter table public.quiz_batches enable row level security;
drop policy if exists "Public can read quiz_batches" on public.quiz_batches;
create policy "Public can read quiz_batches" on public.quiz_batches for select to anon, authenticated using (true);
drop policy if exists "Authenticated can manage quiz_batches" on public.quiz_batches;
create policy "Authenticated can manage quiz_batches" on public.quiz_batches for all to authenticated using (true) with check (true);

alter table public.quiz_questions add column if not exists batch_id bigint references public.quiz_batches(id) on delete set null;
alter table public.quiz_questions add column if not exists sequence_no integer;
alter table public.quiz_questions add column if not exists starts_at timestamptz;
alter table public.quiz_questions add column if not exists ends_at timestamptz;
alter table public.quiz_questions add column if not exists published_at timestamptz;
alter table public.quiz_questions add column if not exists xp_applied boolean not null default false;

-- Old standalone questions are historical only after this migration.
update public.quiz_questions
set published_at = coalesce(published_at, now())
where starts_at is null and published_at is null;
update public.quiz_attempts set xp_applied=true where xp_applied=false;

-- Current public question: never expose correct_option.
drop view if exists public.quiz_questions_public;
create view public.quiz_questions_public as
select id, batch_id, sequence_no, question, option_a, option_b, option_c, option_d, starts_at, ends_at
from public.quiz_questions
where starts_at is not null and starts_at <= now() and now() < ends_at and published_at is null;
grant select on public.quiz_questions_public to anon, authenticated;
revoke select on public.quiz_questions from anon;

-- One attempt per normalized student+class+question.
drop index if exists public.quiz_attempts_one_chance_idx;
create unique index if not exists quiz_attempts_one_chance_idx
on public.quiz_attempts (
  question_id,
  lower(regexp_replace(trim(student_name), '\s+', '', 'g')),
  translate(upper(regexp_replace(trim(class_name), '\s+', '', 'g')), 'ABEKMHOPCTXY', 'АВЕКМНОРСТХУ')
) where question_id is not null;

-- Archive expired questions and award XP exactly once when their 24h window ends.
create or replace function public.sync_daily_quiz_state()
returns void
language plpgsql
security definer
set search_path=public
as $$
declare q record; a record; norm_class text;
begin
  for q in select id from public.quiz_questions where ends_at is not null and ends_at <= now() and published_at is null order by ends_at,id loop
    update public.quiz_questions set published_at=ends_at where id=q.id and published_at is null;
    for a in select id,class_name,score from public.quiz_attempts where question_id=q.id and xp_applied=false loop
      if a.score=1 then
        norm_class:=translate(upper(regexp_replace(trim(a.class_name), '\s+', '', 'g')), 'ABEKMHOPCTXY', 'АВЕКМНОРСТХУ');
        insert into public.class_xp(class_name,xp,updated_at) values(norm_class,1,now())
        on conflict(class_name) do update set xp=public.class_xp.xp+1,updated_at=now();
      end if;
      update public.quiz_attempts set xp_applied=true where id=a.id;
    end loop;
  end loop;
end;
$$;
grant execute on function public.sync_daily_quiz_state() to anon, authenticated;

create or replace function public.get_current_daily_quiz()
returns table(id bigint,batch_id bigint,sequence_no integer,question text,option_a text,option_b text,option_c text,option_d text,starts_at timestamptz,ends_at timestamptz)
language plpgsql security definer set search_path=public as $$
begin
  perform public.sync_daily_quiz_state();
  return query select q.id,q.batch_id,q.sequence_no,q.question,q.option_a,q.option_b,q.option_c,q.option_d,q.starts_at,q.ends_at
  from public.quiz_questions q
  where q.starts_at is not null and q.starts_at <= now() and now() < q.ends_at and q.published_at is null
  order by q.starts_at desc,q.id desc limit 1;
end;
$$;
grant execute on function public.get_current_daily_quiz() to anon, authenticated;

-- (The simple, non-class-limited version of submit_daily_quiz that used to
-- live here was removed — the final, class-limit-aware version further
-- below is the one that's actually active.)


-- Create the whole queue in one admin action. Each question = 24 hours.
create or replace function public.create_daily_quiz_batch(p_start_at timestamptz,p_questions jsonb)
returns bigint
language plpgsql security definer set search_path=public as $$
declare batch_id bigint; actual_start timestamptz; last_end timestamptz; item jsonb; i integer:=0;
begin
  if auth.uid() is null then raise exception 'admin authentication required'; end if;
  if jsonb_typeof(p_questions)<>'array' or jsonb_array_length(p_questions)<1 then raise exception 'questions are required'; end if;
  select max(ends_at) into last_end from public.quiz_questions where ends_at is not null and published_at is null;
  actual_start:=greatest(coalesce(p_start_at,now()),coalesce(last_end,coalesce(p_start_at,now())));
  insert into public.quiz_batches(title,start_at) values('Күнделікті викторина',actual_start) returning id into batch_id;
  for item in select value from jsonb_array_elements(p_questions) loop
    i:=i+1;
    insert into public.quiz_questions(batch_id,sequence_no,question,option_a,option_b,option_c,option_d,correct_option,starts_at,ends_at,published_at,xp_applied)
    values(batch_id,i,item->>'question',item->>'option_a',item->>'option_b',item->>'option_c',item->>'option_d',lower(item->>'correct_option'),actual_start+((i-1)*interval '24 hours'),actual_start+(i*interval '24 hours'),null,false);
  end loop;
  return batch_id;
end;
$$;
grant execute on function public.create_daily_quiz_batch(timestamptz,jsonb) to authenticated;

-- ================================================================
-- BATTLE: start -> 30 minutes -> final results. Server checks answers.
-- ================================================================
alter table public.battle_attempts add column if not exists started_at timestamptz;
alter table public.battle_attempts add column if not exists finished_at timestamptz;
alter table public.battle_attempts add column if not exists duration_seconds integer;
alter table public.battle_attempts add column if not exists completed boolean not null default true;
update public.battle_attempts set started_at=coalesce(started_at,created_at),finished_at=coalesce(finished_at,created_at),duration_seconds=coalesce(duration_seconds,0),completed=true;

create unique index if not exists battle_attempts_one_student_idx on public.battle_attempts(
 battle_id, lower(regexp_replace(trim(student_name),'\s+','','g')),
 translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')
);

-- Never expose correct_option through the public table.
drop view if exists public.battle_questions_public;
create view public.battle_questions_public as
select id,battle_id,question,option_a,option_b,option_c,option_d,created_at from public.battle_questions;
grant select on public.battle_questions_public to anon,authenticated;
revoke select on public.battle_questions from anon;

-- Remove direct anonymous inserts; only the secure RPCs can create/update attempts.
drop policy if exists "Public can submit battle_attempts" on public.battle_attempts;


-- NOTE: an earlier draft of start_battle_attempt used to live here, but its
-- RETURNS TABLE column was named "id" while the final version below (added
-- with the class-limits feature) names it "attempt_id". Since PostgreSQL
-- refuses "CREATE OR REPLACE FUNCTION" when the return type changes, having
-- both in one script would abort the whole migration partway through with
-- "cannot change return type of existing function". Removed the dead draft
-- here so only the working version (further down) is ever created.


create or replace function public.submit_battle_attempt(p_attempt_id bigint,p_answers jsonb)
returns table(score integer,total integer,duration_seconds integer)
language plpgsql security definer set search_path=public as $$
declare a record; q record; ans jsonb; s integer:=0; total_q integer:=0; dur integer;
begin
  select * into a from public.battle_attempts where id=p_attempt_id for update;
  if a.id is null then raise exception 'attempt not found'; end if;
  if a.completed then return query select a.score,a.total,coalesce(a.duration_seconds,0); return; end if;
  dur:=extract(epoch from (now()-a.started_at))::integer;
  if dur>1800 then
    update public.battle_attempts set completed=true,finished_at=a.started_at+interval '30 minutes',duration_seconds=1800 where id=a.id;
    raise exception 'time expired';
  end if;
  for q in select * from public.battle_questions where battle_id=a.battle_id order by created_at,id loop
    total_q:=total_q+1;
    select value into ans from jsonb_array_elements(coalesce(p_answers,'[]'::jsonb)) where (value->>'question_id')::bigint=q.id limit 1;
    if ans is not null and lower(ans->>'answer')=lower(q.correct_option) then s:=s+1; end if;
  end loop;
  dur:=extract(epoch from (now()-a.started_at))::integer;
  update public.battle_attempts set score=s,total=total_q,completed=true,finished_at=now(),duration_seconds=dur where id=a.id;
  return query select s,total_q,dur;
end;
$$;
grant execute on function public.submit_battle_attempt(bigint,jsonb) to anon,authenticated;

-- Ensure result reads remain public; direct attempt inserts are no longer allowed to anon.

-- ================================================================
-- NATIVE READING QUESTS: Google-Forms-like quests inside KITAPVERSE.
-- Each quest has its own questions, one attempt per student/class,
-- server-side answer validation, +1 class XP per correct answer.
-- ================================================================
create table if not exists public.quests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  published boolean not null default true,
  created_at timestamptz default now()
);
alter table public.quests enable row level security;
drop policy if exists "Public can read quests" on public.quests;
create policy "Public can read quests" on public.quests for select to anon, authenticated using (published=true);
drop policy if exists "Authenticated can manage quests" on public.quests;
create policy "Authenticated can manage quests" on public.quests for all to authenticated using (true) with check (true);

create table if not exists public.quest_questions (
  id bigint generated by default as identity primary key,
  quest_id bigint not null references public.quests(id) on delete cascade,
  sequence_no integer not null,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('a','b','c','d')),
  created_at timestamptz default now(),
  unique(quest_id,sequence_no)
);
alter table public.quest_questions enable row level security;
drop policy if exists "Public can read quest_questions_public" on public.quest_questions;
drop policy if exists "Authenticated can manage quest_questions" on public.quest_questions;
create policy "Authenticated can manage quest_questions" on public.quest_questions for all to authenticated using (true) with check (true);

drop view if exists public.quest_questions_public;
create view public.quest_questions_public as
select id,quest_id,sequence_no,question,option_a,option_b,option_c,option_d,created_at
from public.quest_questions;
grant select on public.quest_questions_public to anon, authenticated;
revoke select on public.quest_questions from anon;

create table if not exists public.quest_attempts (
  id bigint generated by default as identity primary key,
  quest_id bigint not null references public.quests(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  score integer not null default 0,
  total integer not null default 0,
  created_at timestamptz default now()
);
alter table public.quest_attempts enable row level security;
drop policy if exists "Public can read quest_attempts" on public.quest_attempts;
create policy "Public can read quest_attempts" on public.quest_attempts for select to anon, authenticated using (true);
drop policy if exists "Public can insert quest_attempts" on public.quest_attempts;
drop policy if exists "Authenticated can manage quest_attempts" on public.quest_attempts;
create policy "Authenticated can manage quest_attempts" on public.quest_attempts for all to authenticated using (true) with check (true);
create unique index if not exists quest_attempts_one_chance_idx on public.quest_attempts(
  quest_id,
  lower(regexp_replace(trim(student_name),'\s+','','g')),
  translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')
);

-- (The 3-argument draft of create_quest_batch that used to live here was
-- removed — the app always calls the 4-argument version below, which also
-- supports linking a quest to a library book.)


create or replace function public.submit_quest_attempt(p_quest_id bigint,p_student_name text,p_class_name text,p_answers jsonb)
returns table(score integer,total integer)
language plpgsql security definer set search_path=public as $$
declare q record; ans jsonb; s integer:=0; t integer:=0; norm_name text; norm_class text; final_score integer;
begin
  if nullif(trim(p_student_name),'') is null or nullif(trim(p_class_name),'') is null then raise exception 'name and class are required'; end if;
  if not exists(select 1 from public.quests where id=p_quest_id and published=true) then raise exception 'quest is not active'; end if;
  norm_name:=lower(regexp_replace(trim(p_student_name),'\s+','','g'));
  norm_class:=translate(upper(regexp_replace(trim(p_class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ');
  if exists(select 1 from public.quest_attempts where quest_id=p_quest_id and lower(regexp_replace(trim(student_name),'\s+','','g'))=norm_name and translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class) then raise exception 'already submitted'; end if;
  for q in select * from public.quest_questions where quest_id=p_quest_id order by sequence_no,id loop
    t:=t+1;
    select value into ans from jsonb_array_elements(coalesce(p_answers,'[]'::jsonb)) where (value->>'question_id')::bigint=q.id limit 1;
    if ans is not null and lower(ans->>'answer')=lower(q.correct_option) then s:=s+1; end if;
  end loop;
  insert into public.quest_attempts(quest_id,student_name,class_name,score,total) values(p_quest_id,trim(p_student_name),trim(p_class_name),s,t);
  if s>0 then
    insert into public.class_xp(class_name,xp,updated_at) values(norm_class,s,now())
    on conflict(class_name) do update set xp=public.class_xp.xp+s,updated_at=now();
    -- Reuse the student-rating stream so quest points appear in the top-5 list.
    insert into public.quiz_attempts(student_name,class_name,score,total,question_id,xp_applied)
    values(trim(p_student_name),trim(p_class_name),s,t,null,true);
  end if;
  return query select s,t;
exception when unique_violation then raise exception 'already submitted';
end; $$;
grant execute on function public.submit_quest_attempt(bigint,text,text,jsonb) to anon, authenticated;

-- ================================================================
-- BATTLE REWARDS: winner class +50 class XP; best individual +10.
-- Rewards are applied once, only after the global 30-minute window.
-- ================================================================
alter table public.battles add column if not exists rewards_applied boolean not null default false;

create or replace function public.finalize_battle_rewards(p_battle_id bigint)
returns table(winner_class text,best_student text,best_class text)
language plpgsql security definer set search_path=public as $$
declare b record; r record; top record; norm_class text;
begin
  select * into b from public.battles where id=p_battle_id for update;
  if b.id is null then raise exception 'battle not found'; end if;
  if now() < b.battle_date + interval '30 minutes' then raise exception 'battle is not finished'; end if;
  if not b.rewards_applied then
    update public.battle_attempts set completed=true,finished_at=b.battle_date+interval '30 minutes',duration_seconds=1800 where battle_id=p_battle_id and completed=false;
    select norm_cls, sum(total_score) total_score, min(label) label into r
    from (select translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ') norm_cls, sum(score) total_score, min(class_name) label
          from public.battle_attempts where battle_id=p_battle_id and completed=true group by 1) x
    group by norm_cls order by sum(total_score) desc, norm_cls asc limit 1;
    select * from public.battle_attempts where battle_id=p_battle_id and completed=true order by score desc,duration_seconds asc,id asc limit 1 into top;
    if r.norm_cls is not null then
      norm_class:=r.norm_cls;
      insert into public.class_xp(class_name,xp,updated_at) values(norm_class,50,now()) on conflict(class_name) do update set xp=public.class_xp.xp+50,updated_at=now();
    end if;
    if top.student_name is not null then
      insert into public.quiz_attempts(student_name,class_name,score,total,question_id,xp_applied) values(trim(top.student_name),trim(top.class_name),10,10,null,true);
    end if;
    update public.battles set rewards_applied=true where id=p_battle_id;
  end if;
  select x.label into winner_class from (select translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ') norm_cls, min(class_name) label, sum(score) total_score from public.battle_attempts where battle_id=p_battle_id and completed=true group by 1) x order by x.total_score desc,x.norm_cls asc limit 1;
  select student_name,class_name from public.battle_attempts where battle_id=p_battle_id and completed=true order by score desc,duration_seconds asc,id asc limit 1 into best_student,best_class;
  return next;
end; $$;
grant execute on function public.finalize_battle_rewards(bigint) to anon, authenticated;

-- ================================================================
-- SCHOOL CLASS LIMITS + NATIVE SCHOOL TESTS
-- ================================================================
create table if not exists public.class_limits (
  id bigint generated by default as identity primary key,
  class_name text not null,
  attempt_limit integer not null check (attempt_limit > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.class_limits enable row level security;
drop policy if exists "Public can read class_limits" on public.class_limits;
create policy "Public can read class_limits" on public.class_limits for select to anon, authenticated using (true);
drop policy if exists "Authenticated can manage class_limits" on public.class_limits;
create policy "Authenticated can manage class_limits" on public.class_limits for all to authenticated using (true) with check (true);
create unique index if not exists class_limits_name_idx on public.class_limits(
  translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')
);

create or replace function public.save_class_limits(p_classes jsonb)
returns void language plpgsql security definer set search_path=public as $$
declare item jsonb; norm text; lim integer;
begin
  if auth.uid() is null then raise exception 'admin authentication required'; end if;
  if jsonb_typeof(p_classes) <> 'array' then raise exception 'classes must be array'; end if;
  for item in select value from jsonb_array_elements(p_classes) loop
    norm:=translate(upper(regexp_replace(trim(item->>'class_name'),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ');
    lim:=greatest(1,(item->>'attempt_limit')::integer);
    if norm='' then continue; end if;
    insert into public.class_limits(class_name,attempt_limit,updated_at) values(norm,lim,now())
    on conflict ((translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')))
    do update set class_name=excluded.class_name,attempt_limit=excluded.attempt_limit,updated_at=now();
  end loop;
end; $$;
grant execute on function public.save_class_limits(jsonb) to authenticated;

-- Native school tests: same Google-Forms-like interface as KITAPVERSE quests.
create table if not exists public.school_tests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.school_tests enable row level security;
drop policy if exists "Public can read school_tests" on public.school_tests;
create policy "Public can read school_tests" on public.school_tests for select to anon, authenticated using (published=true);
drop policy if exists "Authenticated can manage school_tests" on public.school_tests;
create policy "Authenticated can manage school_tests" on public.school_tests for all to authenticated using (true) with check (true);

create table if not exists public.school_test_questions (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.school_tests(id) on delete cascade,
  sequence_no integer not null,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (lower(correct_option) in ('a','b','c','d')),
  created_at timestamptz not null default now()
);
alter table public.school_test_questions enable row level security;
drop policy if exists "Public can read school_test_questions" on public.school_test_questions;
create policy "Public can read school_test_questions" on public.school_test_questions for select to authenticated using (true);
drop policy if exists "Authenticated can manage school_test_questions" on public.school_test_questions;
create policy "Authenticated can manage school_test_questions" on public.school_test_questions for all to authenticated using (true) with check (true);
drop view if exists public.school_test_questions_public;
create view public.school_test_questions_public as select id,test_id,sequence_no,question,option_a,option_b,option_c,option_d,created_at from public.school_test_questions;
grant select on public.school_test_questions_public to anon,authenticated;
revoke select on public.school_test_questions from anon;

create table if not exists public.school_test_attempts (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.school_tests(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  score integer not null default 0,
  total integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.school_test_attempts enable row level security;
drop policy if exists "Public can read school_test_attempts" on public.school_test_attempts;
create policy "Public can read school_test_attempts" on public.school_test_attempts for select to authenticated using (true);
drop policy if exists "Authenticated can manage school_test_attempts" on public.school_test_attempts;
create policy "Authenticated can manage school_test_attempts" on public.school_test_attempts for all to authenticated using (true) with check (true);
create unique index if not exists school_test_attempt_one_chance_idx on public.school_test_attempts(
  test_id,
  lower(regexp_replace(trim(student_name),'\s+','','g')),
  translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')
);

create or replace function public.create_school_test_batch(p_title text,p_description text,p_questions jsonb)
returns bigint language plpgsql security definer set search_path=public as $$
declare tid bigint; item jsonb; i integer:=0;
begin
  if auth.uid() is null then raise exception 'admin authentication required'; end if;
  insert into public.school_tests(title,description,published) values(trim(p_title),nullif(trim(p_description),''),true) returning id into tid;
  for item in select value from jsonb_array_elements(p_questions) loop
    i:=i+1;
    insert into public.school_test_questions(test_id,sequence_no,question,option_a,option_b,option_c,option_d,correct_option)
    values(tid,i,item->>'question',item->>'option_a',item->>'option_b',item->>'option_c',item->>'option_d',lower(item->>'correct_option'));
  end loop;
  return tid;
end; $$;
grant execute on function public.create_school_test_batch(text,text,jsonb) to authenticated;

create or replace function public.submit_school_test_attempt(p_test_id bigint,p_student_name text,p_class_name text,p_answers jsonb)
returns table(score integer,total integer)
language plpgsql security definer set search_path=public as $$
declare q record; ans jsonb; s integer:=0; t integer:=0; norm_class text; norm_name text;
begin
  if nullif(trim(p_student_name),'') is null or nullif(trim(p_class_name),'') is null then raise exception 'name and class are required'; end if;
  if not exists(select 1 from public.school_tests where id=p_test_id and published=true) then raise exception 'test is not active'; end if;
  norm_name:=lower(regexp_replace(trim(p_student_name),'\s+','','g'));
  norm_class:=translate(upper(regexp_replace(trim(p_class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ');
  if exists(select 1 from public.school_test_attempts where test_id=p_test_id and lower(regexp_replace(trim(student_name),'\s+','','g'))=norm_name and translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class) then raise exception 'already submitted'; end if;
  for q in select * from public.school_test_questions where test_id=p_test_id order by sequence_no,id loop
    t:=t+1;
    select value into ans from jsonb_array_elements(coalesce(p_answers,'[]'::jsonb)) where (value->>'question_id')::bigint=q.id limit 1;
    if ans is not null and lower(ans->>'answer')=lower(q.correct_option) then s:=s+1; end if;
  end loop;
  insert into public.school_test_attempts(test_id,student_name,class_name,score,total) values(p_test_id,trim(p_student_name),trim(p_class_name),s,t);
  return query select s,t;
exception when unique_violation then raise exception 'already submitted';
end; $$;
grant execute on function public.submit_school_test_attempt(bigint,text,text,jsonb) to anon,authenticated;

-- Daily quiz: class must exist in class_limits and each class has a fixed number of attempts per question.
create or replace function public.submit_daily_quiz(p_question_id bigint,p_student_name text,p_class_name text,p_answer text)
returns table(score integer,total integer)
language plpgsql security definer set search_path=public as $$
declare q record; norm_name text; norm_class text; lim integer; used integer; final_score integer;
begin
  perform public.sync_daily_quiz_state();
  if nullif(trim(p_student_name),'') is null or nullif(trim(p_class_name),'') is null then raise exception 'name and class are required'; end if;
  norm_name:=lower(regexp_replace(trim(p_student_name),'\s+','','g'));
  norm_class:=translate(upper(regexp_replace(trim(p_class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ');
  select attempt_limit into lim from public.class_limits where translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class;
  if lim is null then raise exception 'class is not configured'; end if;
  select * into q from public.quiz_questions where id=p_question_id and starts_at<=now() and now()<ends_at and published_at is null;
  if q.id is null then raise exception 'quiz is not active'; end if;
  select count(*) into used from public.quiz_attempts where question_id=p_question_id and translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class;
  if used >= lim then raise exception 'class limit reached'; end if;
  if exists(select 1 from public.quiz_attempts a where a.question_id=p_question_id and lower(regexp_replace(trim(a.student_name),'\s+','','g'))=norm_name and translate(upper(regexp_replace(trim(a.class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class) then raise exception 'already submitted'; end if;
  final_score:=case when lower(trim(p_answer))=lower(q.correct_option) then 1 else 0 end;
  insert into public.quiz_attempts(student_name,class_name,score,total,question_id,xp_applied) values(trim(p_student_name),trim(p_class_name),final_score,1,p_question_id,false);
  return query select final_score,1;
end; $$;
grant execute on function public.submit_daily_quiz(bigint,text,text,text) to anon,authenticated;

-- Battle: fixed class capacity per battle. Every attempt consumes one slot, even if the name is wrong.
create or replace function public.start_battle_attempt(p_battle_id bigint,p_student_name text,p_class_name text)
returns table(attempt_id bigint,started_at timestamptz)
language plpgsql security definer set search_path=public as $$
declare b record; existing record; norm_name text; norm_class text; lim integer; used integer; allowed boolean;
begin
  if nullif(trim(p_student_name),'') is null or nullif(trim(p_class_name),'') is null then raise exception 'name and class are required'; end if;
  select * into b from public.battles where id=p_battle_id;
  if b.id is null then raise exception 'battle not found'; end if;
  if now() < b.battle_date then raise exception 'battle is not active'; end if;
  if now() >= b.battle_date + interval '30 minutes' then raise exception 'battle is over'; end if;
  norm_name:=lower(regexp_replace(trim(p_student_name),'\s+','','g'));
  norm_class:=translate(upper(regexp_replace(trim(p_class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ');
  select attempt_limit into lim from public.class_limits where translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class;
  if lim is null then raise exception 'class is not configured'; end if;
  allowed:=exists(select 1 from unnest(string_to_array(regexp_replace(coalesce(b.classes,''),'\s*,\s*',','),',')) x where translate(upper(trim(x)),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class);
  if not allowed then raise exception 'class is not participating'; end if;
  select * into existing from public.battle_attempts where battle_id=p_battle_id and lower(regexp_replace(trim(student_name),'\s+','','g'))=norm_name and translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class limit 1;
  if existing.id is not null then
    if existing.completed then raise exception 'already submitted'; end if;
    return query select existing.id,existing.started_at; return;
  end if;
  select count(*) into used from public.battle_attempts where battle_id=p_battle_id and translate(upper(regexp_replace(trim(class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ')=norm_class;
  if used >= lim then raise exception 'class limit reached'; end if;
  insert into public.battle_attempts(battle_id,student_name,class_name,score,total,started_at,completed) values(p_battle_id,trim(p_student_name),trim(p_class_name),0,(select count(*) from public.battle_questions where battle_id=p_battle_id),b.battle_date,false) returning id,started_at into attempt_id,started_at;
  return next;
end; $$;
grant execute on function public.start_battle_attempt(bigint,text,text) to anon,authenticated;

-- Enforce quiz class limits server-side: public clients must use submit_daily_quiz RPC.
drop policy if exists "Public can submit quiz_attempts" on public.quiz_attempts;

-- ===== KITAPVERSE: Student profiles + reading progress =====
create table if not exists public.student_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  iin_login text unique not null,
  full_name text not null,
  class_name text not null,
  active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.student_profiles enable row level security;
drop policy if exists "Students can read own profile" on public.student_profiles;
create policy "Students can read own profile" on public.student_profiles
  for select to authenticated using (auth.uid() = auth_user_id);
drop policy if exists "Authenticated can manage student profiles" on public.student_profiles;
create policy "Authenticated can manage student profiles" on public.student_profiles
  for all to authenticated using (true) with check (true);

alter table public.library_books add column if not exists drive_url text;
alter table public.library_books add column if not exists quest_id bigint references public.quests(id) on delete set null;

create table if not exists public.book_progress (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.student_profiles(id) on delete cascade,
  book_id bigint not null references public.library_books(id) on delete cascade,
  marked_read_at timestamptz default now(),
  unique(student_id, book_id)
);
alter table public.book_progress enable row level security;
drop policy if exists "Students can read own book progress" on public.book_progress;
create policy "Students can read own book progress" on public.book_progress
  for select to authenticated using (
    student_id in (select id from public.student_profiles where auth_user_id = auth.uid())
  );
drop policy if exists "Students can mark own books read" on public.book_progress;
create policy "Students can mark own books read" on public.book_progress
  for insert to authenticated with check (
    student_id in (select id from public.student_profiles where auth_user_id = auth.uid())
  );
drop policy if exists "Students can update own book progress" on public.book_progress;
create policy "Students can update own book progress" on public.book_progress
  for update to authenticated using (
    student_id in (select id from public.student_profiles where auth_user_id = auth.uid())
  ) with check (
    student_id in (select id from public.student_profiles where auth_user_id = auth.uid())
  );

grant select on public.student_profiles to authenticated;
grant select,insert,update on public.book_progress to authenticated;


-- Quest ↔ Book link for the reading flow.
alter table public.quests add column if not exists book_id bigint references public.library_books(id) on delete set null;
create or replace function public.create_quest_batch(p_title text,p_description text,p_book_id bigint,p_questions jsonb)
returns bigint language plpgsql security definer set search_path=public as $$
declare qid bigint; item jsonb; i integer:=0;
begin
  if auth.uid() is null then raise exception 'admin authentication required'; end if;
  if nullif(trim(p_title),'') is null then raise exception 'title is required'; end if;
  if jsonb_typeof(p_questions)<>'array' or jsonb_array_length(p_questions)<1 then raise exception 'questions are required'; end if;
  insert into public.quests(title,description,book_id,published) values(trim(p_title),nullif(trim(p_description),''),p_book_id,true) returning id into qid;
  for item in select value from jsonb_array_elements(p_questions) loop
    i:=i+1;
    insert into public.quest_questions(quest_id,sequence_no,question,option_a,option_b,option_c,option_d,correct_option)
    values(qid,i,item->>'question',item->>'option_a',item->>'option_b',item->>'option_c',item->>'option_d',lower(item->>'correct_option'));
  end loop;
  return qid;
end; $$;
grant execute on function public.create_quest_batch(text,text,bigint,jsonb) to authenticated;

-- Automatically links a signed-in Auth user to the preloaded student profile
-- by matching the synthetic Auth email convention: IIN@students.kitapverse.local.
create or replace function public.claim_my_student_profile()
returns public.student_profiles
language plpgsql security definer set search_path=public as $$
declare
  v_iin text;
  v_row public.student_profiles;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  v_iin := split_part(coalesce(auth.jwt()->>'email',''),'@',1);
  if v_iin is null or v_iin='' then raise exception 'student login email is invalid'; end if;
  update public.student_profiles
    set auth_user_id=auth.uid(), updated_at=now()
    where iin_login=v_iin and (auth_user_id is null or auth_user_id=auth.uid()) and active=true
    returning * into v_row;
  if not found then raise exception 'student profile not found'; end if;
  return v_row;
end; $$;
grant execute on function public.claim_my_student_profile() to authenticated;

-- ===== Admin-only write protection after student accounts are enabled =====
create or replace function public.is_kitapverse_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select coalesce(auth.jwt()->>'email','') = 'imankulovmagzan56@gmail.com';
$$;
grant execute on function public.is_kitapverse_admin() to anon, authenticated;

-- Existing write policies were originally authenticated-only. Once students have
-- Auth accounts, restrict those write paths to the dedicated admin account.
alter policy "Authenticated can manage achievements" on public.achievements using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can update news" on public.news using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can delete news" on public.news using (public.is_kitapverse_admin());
alter policy "Authenticated can update documents" on public.documents using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can delete documents" on public.documents using (public.is_kitapverse_admin());
alter policy "Authenticated can manage library_books" on public.library_books using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage class_xp" on public.class_xp using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage kv_settings" on public.kv_settings using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage quiz_questions" on public.quiz_questions using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can delete quiz_attempts" on public.quiz_attempts using (public.is_kitapverse_admin());
alter policy "Authenticated can manage rewards" on public.rewards using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage battles" on public.battles using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage battle_questions" on public.battle_questions using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can delete battle_attempts" on public.battle_attempts using (public.is_kitapverse_admin());
alter policy "Authenticated can manage quiz_batches" on public.quiz_batches using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage quests" on public.quests using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage quest_questions" on public.quest_questions using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage quest_attempts" on public.quest_attempts using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage class_limits" on public.class_limits using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage school_tests" on public.school_tests using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage school_test_questions" on public.school_test_questions using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage school_test_attempts" on public.school_test_attempts using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());
alter policy "Authenticated can manage student profiles" on public.student_profiles using (public.is_kitapverse_admin()) with check (public.is_kitapverse_admin());

-- ================================================================
-- PHASE 1: secure "read → quest → verify → XP" pipeline.
-- Previously a student could insert/update book_progress directly from
-- the browser, marking any book "read" with no quest check at all.
-- From now on: the client can only DECLARE intent to read (which requires
-- a quest to already exist for that book) and SUBMIT quest answers; the
-- server alone decides whether the book becomes "verified" and whether
-- XP is granted — and only once per student per book, ever.
-- ================================================================

alter table public.book_progress add column if not exists verified boolean not null default false;
alter table public.book_progress add column if not exists xp_awarded boolean not null default false;
alter table public.book_progress add column if not exists verified_at timestamptz;

-- Students can no longer write to book_progress directly — only read it.
-- (SECURITY DEFINER functions below bypass RLS to do the actual writes.)
drop policy if exists "Students can mark own books read" on public.book_progress;
drop policy if exists "Students can update own book progress" on public.book_progress;
revoke insert, update on public.book_progress from authenticated;

-- Step 1: student presses "Мен оқыдым" — this only "declares" intent and
-- requires a quest to already be linked to the book, otherwise it fails
-- with a clear reason the UI can show ("no_quest").
create or replace function public.declare_book_read(p_book_id bigint)
returns table(quest_id bigint, already_verified boolean)
language plpgsql security definer set search_path=public as $$
declare sid bigint; qid bigint; bp record;
begin
  if auth.uid() is null then raise exception 'login required'; end if;
  select id into sid from public.student_profiles where auth_user_id=auth.uid();
  if sid is null then raise exception 'student profile not linked'; end if;

  select id into qid from public.quests where book_id=p_book_id and published=true order by created_at desc limit 1;
  if qid is null then raise exception 'no_quest'; end if;

  select * into bp from public.book_progress where student_id=sid and book_id=p_book_id;
  if bp.id is null then
    insert into public.book_progress(student_id,book_id,marked_read_at) values(sid,p_book_id,now());
    return query select qid, false;
  else
    return query select qid, bp.verified;
  end if;
end; $$;
grant execute on function public.declare_book_read(bigint) to authenticated;

-- Step 2: student submits answers for a book-linked quest. The server
-- grades it, and only marks the book "verified" + awards +50 XP the
-- FIRST time a student passes — repeat attempts never re-award XP.
-- Passing bar: at least 60% correct (rounded up).
create or replace function public.submit_book_quest_attempt(p_quest_id bigint, p_answers jsonb)
returns table(score integer, total integer, passed boolean, xp_awarded integer)
language plpgsql security definer set search_path=public as $$
declare
  sid bigint; sp record; qrow record; bp record; q record; ans jsonb;
  s integer:=0; t integer:=0; did_pass boolean; awarded integer:=0; norm_class text;
begin
  if auth.uid() is null then raise exception 'login required'; end if;
  select * into sp from public.student_profiles where auth_user_id=auth.uid();
  if sp.id is null then raise exception 'student profile not linked'; end if;
  sid := sp.id;

  select * into qrow from public.quests where id=p_quest_id and published=true;
  if qrow.id is null then raise exception 'quest is not active'; end if;
  if qrow.book_id is null then raise exception 'not a book quest'; end if;

  select * into bp from public.book_progress where student_id=sid and book_id=qrow.book_id;
  if bp.id is null then raise exception 'book not declared as read yet'; end if;

  for q in select * from public.quest_questions where quest_id=p_quest_id order by sequence_no,id loop
    t:=t+1;
    select value into ans from jsonb_array_elements(coalesce(p_answers,'[]'::jsonb)) where (value->>'question_id')::bigint=q.id limit 1;
    if ans is not null and lower(ans->>'answer')=lower(q.correct_option) then s:=s+1; end if;
  end loop;
  if t=0 then raise exception 'quest has no questions'; end if;

  did_pass := s >= ceil(t*0.6);
  norm_class := translate(upper(regexp_replace(trim(sp.class_name),'\s+','','g')),'ABEKMHOPCTXY','АВЕКМНОРСТХУ');

  insert into public.quest_attempts(quest_id,student_name,class_name,score,total)
  values(p_quest_id,sp.full_name,sp.class_name,s,t);

  if did_pass and not bp.xp_awarded then
    update public.book_progress set verified=true, xp_awarded=true, verified_at=now() where id=bp.id;
    insert into public.class_xp(class_name,xp,updated_at) values(norm_class,50,now())
      on conflict(class_name) do update set xp=public.class_xp.xp+50, updated_at=now();
    insert into public.quiz_attempts(student_name,class_name,score,total,question_id,xp_applied)
      values(sp.full_name,sp.class_name,50,50,null,true);
    awarded := 50;
  elsif did_pass then
    -- Already verified before: let them retake for practice, but never pay twice.
    awarded := 0;
  end if;

  return query select s, t, did_pass, awarded;
end; $$;
grant execute on function public.submit_book_quest_attempt(bigint,jsonb) to authenticated;

