-- Run this ONCE in Supabase SQL Editor.
-- This adds the fields the website needs to the tables you already created.
alter table public.news
  add column if not exists published_date date default current_date;

alter table public.documents
  add column if not exists file_name text;

alter table public.documents
  add column if not exists storage_path text;

-- Optional: make existing news have today's date if the new column is null.
update public.news set published_date = current_date where published_date is null;

-- ===== New table: achievements (Жетістіктер) =====
-- This table did not exist before, so it needs RLS policies of its own.
-- If your news/documents tables use different policy names, adjust to match.
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  icon text default '🏆',
  title text not null,
  description text not null,
  created_at timestamptz default now()
);

alter table public.achievements enable row level security;

-- Anyone (including anonymous site visitors) can read achievements.
drop policy if exists "Public can read achievements" on public.achievements;
create policy "Public can read achievements"
  on public.achievements for select
  to anon, authenticated
  using (true);

-- Only a signed-in admin (Supabase Auth user) can add/edit/delete achievements.
drop policy if exists "Authenticated can manage achievements" on public.achievements;
create policy "Authenticated can manage achievements"
  on public.achievements for all
  to authenticated
  using (true)
  with check (true);

-- ===== Make sure edit/delete also work on news & documents =====
-- Your original setup likely only had INSERT + SELECT policies for the admin
-- (since the old site could only add, never edit/delete). These add UPDATE and
-- DELETE for the signed-in admin so the new edit/delete buttons work too.
drop policy if exists "Authenticated can update news" on public.news;
create policy "Authenticated can update news"
  on public.news for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated can delete news" on public.news;
create policy "Authenticated can delete news"
  on public.news for delete to authenticated using (true);

drop policy if exists "Authenticated can update documents" on public.documents;
create policy "Authenticated can update documents"
  on public.documents for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated can delete documents" on public.documents;
create policy "Authenticated can delete documents"
  on public.documents for delete to authenticated using (true);

-- ===== KITAPVERSE: library_books (Кітапхана) =====
create table if not exists public.library_books (
  id bigint generated by default as identity primary key,
  icon text default '📕',
  title text not null,
  author text,
  description text,
  created_at timestamptz default now()
);

alter table public.library_books enable row level security;

drop policy if exists "Public can read library_books" on public.library_books;
create policy "Public can read library_books"
  on public.library_books for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage library_books" on public.library_books;
create policy "Authenticated can manage library_books"
  on public.library_books for all
  to authenticated
  using (true)
  with check (true);

-- ===== KITAPVERSE: class_xp (Рейтинг тақтасы) =====
-- One row per class (e.g. "7А"), xp is the running total.
-- The admin form adds points to this total; it never needs student logins.
create table if not exists public.class_xp (
  id bigint generated by default as identity primary key,
  class_name text not null unique,
  xp integer not null default 0,
  updated_at timestamptz default now()
);

alter table public.class_xp enable row level security;

drop policy if exists "Public can read class_xp" on public.class_xp;
create policy "Public can read class_xp"
  on public.class_xp for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage class_xp" on public.class_xp;
create policy "Authenticated can manage class_xp"
  on public.class_xp for all
  to authenticated
  using (true)
  with check (true);

-- ===== News photo support =====
-- Photos are stored in the same "documents" storage bucket, under a "news/" path.
alter table public.news
  add column if not exists photo_url text;

alter table public.news
  add column if not exists photo_path text;

-- ===== Library: PDF books + grade grouping (6–10 сынып) =====
alter table public.library_books
  add column if not exists grade int;

alter table public.library_books
  add column if not exists pdf_url text;

alter table public.library_books
  add column if not exists pdf_path text;

-- ===== Site settings (key/value) — used for the Google Forms link for Квесттер =====
create table if not exists public.kv_settings (
  key text primary key,
  value text
);

alter table public.kv_settings enable row level security;

drop policy if exists "Public can read kv_settings" on public.kv_settings;
create policy "Public can read kv_settings"
  on public.kv_settings for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage kv_settings" on public.kv_settings;
create policy "Authenticated can manage kv_settings"
  on public.kv_settings for all
  to authenticated
  using (true)
  with check (true);

-- ===== Quiz questions (Викторина) — admin-authored multiple choice =====
create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('a','b','c','d')),
  created_at timestamptz default now()
);

alter table public.quiz_questions enable row level security;

drop policy if exists "Public can read quiz_questions" on public.quiz_questions;
create policy "Public can read quiz_questions"
  on public.quiz_questions for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage quiz_questions" on public.quiz_questions;
create policy "Authenticated can manage quiz_questions"
  on public.quiz_questions for all
  to authenticated
  using (true)
  with check (true);

-- ===== Quiz attempts — one row per student submission, feeds Battle + student rating =====
create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  student_name text not null,
  class_name text not null,
  score int not null,
  total int not null,
  created_at timestamptz default now()
);

alter table public.quiz_attempts enable row level security;

-- Anyone can read results (needed for the public Battle/rating boards) and
-- anyone (including anonymous students) can submit an attempt — but never
-- update or delete one, so results cannot be tampered with after submission.
drop policy if exists "Public can read quiz_attempts" on public.quiz_attempts;
create policy "Public can read quiz_attempts"
  on public.quiz_attempts for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can submit quiz_attempts" on public.quiz_attempts;
create policy "Public can submit quiz_attempts"
  on public.quiz_attempts for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Authenticated can delete quiz_attempts" on public.quiz_attempts;
create policy "Authenticated can delete quiz_attempts"
  on public.quiz_attempts for delete
  to authenticated
  using (true);

-- ===== Rewards (Марапаттау) =====
create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  position text not null,
  icon text default '🏆',
  title text not null,
  created_at timestamptz default now()
);

alter table public.rewards enable row level security;

drop policy if exists "Public can read rewards" on public.rewards;
create policy "Public can read rewards"
  on public.rewards for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage rewards" on public.rewards;
create policy "Authenticated can manage rewards"
  on public.rewards for all
  to authenticated
  using (true)
  with check (true);
