-- Run this ONCE in Supabase SQL Editor (after supabase-migration.sql).
-- Adds the Battle feature: scheduled class-vs-class events with their own
-- quiz-style questions and a countdown timer on the site.

-- ===== battles: one row per battle event (admin creates: title, classes, date) =====
create table if not exists public.battles (
  id bigint generated by default as identity primary key,
  title text not null,
  classes text not null,               -- e.g. "8А, 9Б" (free text, comma separated)
  battle_date timestamptz not null,    -- when the battle starts (countdown target)
  created_at timestamptz default now()
);

alter table public.battles enable row level security;

drop policy if exists "Public can read battles" on public.battles;
create policy "Public can read battles"
  on public.battles for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage battles" on public.battles;
create policy "Authenticated can manage battles"
  on public.battles for all
  to authenticated
  using (true)
  with check (true);

-- ===== battle_questions: quiz questions that belong to one specific battle =====
create table if not exists public.battle_questions (
  id bigint generated by default as identity primary key,
  battle_id bigint not null references public.battles(id) on delete cascade,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('a','b','c','d')),
  created_at timestamptz default now()
);

alter table public.battle_questions enable row level security;

drop policy if exists "Public can read battle_questions" on public.battle_questions;
create policy "Public can read battle_questions"
  on public.battle_questions for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can manage battle_questions" on public.battle_questions;
create policy "Authenticated can manage battle_questions"
  on public.battle_questions for all
  to authenticated
  using (true)
  with check (true);

-- ===== battle_attempts: one row per student submission for a battle =====
create table if not exists public.battle_attempts (
  id bigint generated by default as identity primary key,
  battle_id bigint not null references public.battles(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  score int not null,
  total int not null,
  created_at timestamptz default now()
);

alter table public.battle_attempts enable row level security;

drop policy if exists "Public can read battle_attempts" on public.battle_attempts;
create policy "Public can read battle_attempts"
  on public.battle_attempts for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can submit battle_attempts" on public.battle_attempts;
create policy "Public can submit battle_attempts"
  on public.battle_attempts for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Authenticated can delete battle_attempts" on public.battle_attempts;
create policy "Authenticated can delete battle_attempts"
  on public.battle_attempts for delete
  to authenticated
  using (true);

-- ===== class_xp: fix classes that "disappear" from the rating (e.g. "8А") =====
-- Root cause: the same class was saved under slightly different spellings —
-- extra spaces ("8 А") or Latin letters that look identical to Cyrillic ones
-- ("8A" typed with an English keyboard). Each spelling became its own row,
-- splitting/hiding that class's points. This merges them into one row per
-- class using the *Cyrillic* spelling, summing the XP. Safe to run more than once.
with normalized as (
  select id, xp, translate(upper(trim(class_name)), 'ABEKMHOPCTXY', 'АВЕКМНОРСТХУ') as norm_name
  from public.class_xp
),
merged as (
  select norm_name, sum(xp) as total_xp, min(id) as keep_id
  from normalized
  group by norm_name
)
update public.class_xp cx
set class_name = m.norm_name, xp = m.total_xp, updated_at = now()
from merged m
where cx.id = m.keep_id;

delete from public.class_xp cx
using normalized n, merged m
where n.id = cx.id and n.norm_name = m.norm_name and cx.id <> m.keep_id;
