-- Run this ONCE in Supabase SQL Editor.
-- This adds the fields the website needs to the tables you already created.
alter table public.news
  add column if not exists published_date date default current_date;

alter table public.documents
  add column if not exists file_name text;

alter table public.documents
  add column if not exists storage_path text;

-- Optional: make existing news have today's date if the new column is null.
update public.news set published_date = current_date where published_date is null;

-- ===== New table: achievements (Жетістіктер) =====
-- This table did not exist before, so it needs RLS policies of its own.
-- If your news/documents tables use different policy names, adjust to match.
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  icon text default '🏆',
  title text not null,
  description text not null,
  created_at timestamptz default now()
);

alter table public.achievements enable row level security;

-- Anyone (including anonymous site visitors) can read achievements.
drop policy if exists "Public can read achievements" on public.achievements;
create policy "Public can read achievements"
  on public.achievements for select
  to anon, authenticated
  using (true);

-- Only a signed-in admin (Supabase Auth user) can add/edit/delete achievements.
drop policy if exists "Authenticated can manage achievements" on public.achievements;
create policy "Authenticated can manage achievements"
  on public.achievements for all
  to authenticated
  using (true)
  with check (true);

-- ===== Make sure edit/delete also work on news & documents =====
-- Your original setup likely only had INSERT + SELECT policies for the admin
-- (since the old site could only add, never edit/delete). These add UPDATE and
-- DELETE for the signed-in admin so the new edit/delete buttons work too.
drop policy if exists "Authenticated can update news" on public.news;
create policy "Authenticated can update news"
  on public.news for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated can delete news" on public.news;
create policy "Authenticated can delete news"
  on public.news for delete to authenticated using (true);

drop policy if exists "Authenticated can update documents" on public.documents;
create policy "Authenticated can update documents"
  on public.documents for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated can delete documents" on public.documents;
create policy "Authenticated can delete documents"
  on public.documents for delete to authenticated using (true);
